# UFC Retirement Age - Preprocessing and Training Data Development

## 1. Contents
* [1. Contents](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
* [2. Sourcing and Loading](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [2a. Import relevant libraries](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [2b. Load previously explored DataFrame](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [2c. Preliminary exploration of data](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
* [3. Additional Data Wrangling](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [3a. Datatype Conversion](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [3b. Cleanup of `country`](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
* [4. Encoding Categorical Variables](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [4a. Removing `finish_details`](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [4b. Dummy encoding every categorical variable except `fighter`](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
* [5. Scaling numerical variables](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
* [6. Combine all preprocessed DataFrames](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [6a. Drop original colummns](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [6b. Concatenate preprocessed DataFrames](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
 * [6c. Save DataFrame](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)
* [7. Final Thoughts](#_UFC_Retirement_Age_-_Preprocessing_and_Training_Data_Development)

## 2. Sourcing and Loading

**2a. Import relevant libraries**

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import kaggle as kg
import pandas as pd
import missingno as msno
import statsmodels.api as sm
import scipy.stats
from matplotlib.lines import Line2D
from kaggle.api.kaggle_api_extended import KaggleApi
from statsmodels.graphics.api import abline_plot
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model, preprocessing
from zipfile import ZipFile
from scipy import stats
from scipy.stats import t
from scipy.stats import ttest_ind
from scipy.stats import mannwhitneyu
from numpy.random import seed
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

**2b. Load previously explored Dataframe**

In [2]:
df = pd.read_csv('df.csv', index_col=0)

**2c. Preliminary exploration of data**

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8774 entries, 0 to 8773
Data columns (total 68 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   date                        8774 non-null   object
 1   fighter                     8774 non-null   object
 2   odds                        8774 non-null   int64
 3   country                     8774 non-null   object
 4   Winner                      8774 non-null   bool
 5   title_bout                  8774 non-null   bool
 6   weight_class                8774 non-null   object
 7   gender                      8774 non-null   object
 8   current_lose_streak         8774 non-null   int64
 9   current_win_streak          8774 non-null   int64
 10  draw                        8774 non-null   int64
 11  avg_SIG_STR_landed          7389 non-null   float64
 12  avg_SIG_STR_pct             7652 non-null   float64
 13  avg_SUB_ATT                 7585 non-null   float64
 14  avg_TD_landed               7584 non-null   float64
 15  avg_TD_pct                  7565 non-null   float64
 16  longest_win_streak          8774 non-null   int64
 17  losses                      8774 non-null   int64
 18  total_rounds_fought         8774 non-null   int64
 19  total_title_bouts           8774 non-null   int64
 20  win_by_Decision_Majority    8774 non-null   int64
 21  win_by_Decision_Split       8774 non-null   int64
 22  win_by_Decision_Unanimous   8774 non-null   int64
 23  win_by_KO/TKO               8774 non-null   int64
 24  win_by_Submission           8774 non-null   int64
 25  win_by_TKO_Doctor_Stoppage  8774 non-null   int64
 26  wins                        8774 non-null   int64
 27  Stance                      8774 non-null   object
 28  Height_cms                  8774 non-null   float64
 29  Reach_cms                   8774 non-null   float64
 30  Weight_lbs                  8774 non-null   int64
 31  age                         8774 non-null   int64
 32  better_rank                 8774 non-null   bool
 33  finish                      8236 non-null   float64
 34  finish_details              4028 non-null   object
 35  finish_round                8198 non-null   float64
 36  finish_round_time           8198 non-null   object
 37  total_fight_time_secs       8198 non-null   float64
 38  kd_bout                     5544 non-null   float64
 39  sig_str_landed_bout         5544 non-null   float64
 40  sig_str_attempted_bout      5544 non-null   float64
 41  sig_str_pct_bout            5544 non-null   float64
 42  tot_str_landed_bout         5544 non-null   float64
 43  tot_str_attempted_bout      5544 non-null   float64
 44  td_landed_bout              5544 non-null   float64
 45  td_attempted_bout           5544 non-null   float64
 46  td_pct_bout                 5544 non-null   float64
 47  sub_attempts_bout           5544 non-null   float64
 48  pass_bout                   5544 non-null   float64
 49  rev_bout                    5544 non-null   float64
 50  win_pct                     8774 non-null   float64
 51  adj_wins                    8774 non-null   int64
 52  current_lose_streak_dif     8774 non-null   int64
 53  current_win_streak_dif      8774 non-null   int64
 54  longest_win_streak_dif      8774 non-null   int64
 55  wins_dif                    8774 non-null   int64
 56  losses_dif                  8774 non-null   int64
 57  total_rounds_fought_dif     8774 non-null   int64
 58  total_title_bouts_dif       8774 non-null   int64
 59  win_by_Submission_dif       8774 non-null   int64
 60  Height_cms_dif              8774 non-null   float64
 61  Reach_cms_dif               8774 non-null   float64
 62  age_dif                     8774 non-null   int64
 63  avg_SIG_STR_landed_dif      6692 non-null   float64
 64  avg_SUB_ATT_dif             6888 non-null   float64
 65  avg_TD_landed_dif           6886 non-null   float64
 66  ko_dif                      8774 non-null   int64
 67  adj_wins_dif                8774 non-null   int64
dtypes: bool(3), float64(28), int64(29), object(8)
memory usage: 4.4+ MB
None

In [4]:
print('Shape: ' + str(df.shape))

Shape: (8774, 68)

In [5]:
df.head()

,date,fighter,odds,country,Winner,title_bout,weight_class,gender,current_lose_streak,current_win_streak,...,total_title_bouts_dif,win_by_Submission_dif,Height_cms_dif,Reach_cms_dif,age_dif,avg_SIG_STR_landed_dif,avg_SUB_ATT_dif,avg_TD_landed_dif,ko_dif,adj_wins_dif
0,2020-09-19,Colby Covington,-335,USA,True,False,Welterweight,MALE,1,0,...,-5,-2,5.08,-5.08,-6,1.79,-0.2,3.80,-4,-20
1,2020-09-19,Tyron Woodley,260,USA,False,False,Welterweight,MALE,2,0,...,5,2,-5.08,5.08,6,-1.79,0.2,-3.80,4,20
2,2020-09-19,Khamzat Chimaev,-400,USA,True,False,Middleweight,MALE,0,2,...,0,-4,2.54,-5.08,-6,5.57,1.5,2.47,0,-16
3,2020-09-19,Gerald Meerschaert,300,USA,False,False,Middleweight,MALE,1,0,...,0,4,-2.54,5.08,6,-5.57,-1.5,-2.47,0,16
4,2020-09-19,Johnny Walker,-125,USA,True,False,Light Heavyweight,MALE,2,0,...,0,-1,2.54,7.62,-1,0.69,-0.6,-0.70,2,0

## 3. Additional Data Wrangling

**3a. Datatype conversion**

In [6]:
df.dtypes[df.dtypes == 'object']

date                 object
fighter              object
country              object
weight_class         object
gender               object
Stance               object
finish_details       object
finish_round_time    object
dtype: object

It looks like `date` and `finish_round_time` can be converted to DateTime and Float format, respectively.

In [7]:
df['date'] = pd.to_datetime(df['date'])
df.date.dtypes

dtype('<M8[ns]')

In [8]:
df['finish_round_time'].value_counts(dropna=False)

5:00    4108
NaN      576
4:59      56
2:38      42
1:54      34
        ...
3:55       2
3:20       2
0:37       2
4:04       2
0:09       2
Name: finish_round_time, Length: 294, dtype: int64

In [9]:
df['finish_round_time'] = pd.to_timedelta('00:' + df['finish_round_time'])
df['finish_round_time'] = df['finish_round_time'] / pd.offsets.Minute(1)

In [10]:
df['finish_round_time'].value_counts(dropna=False)

5.000000    4108
NaN          576
4.983333      56
2.633333      42
1.900000      34
            ...
4.000000       2
4.066667       2
0.083333       2
3.333333       2
0.150000       2
Name: finish_round_time, Length: 294, dtype: int64

**3b. Cleanup of `country`**

In [11]:
df['country'].value_counts()

 USA                     4900
 Brazil                   800
 Canada                   674
USA                       360
 United Kingdom           330
 Australia                320
 Sweden                   144
 Mexico                   140
 China                    122
 Germany                  108
 Japan                    106
United Arab Emirates      102
 Singapore                 90
 Russia                    72
 New Zealand               66
 United Arab Emirates      58
 Netherlands               50
 South Korea               48
 Poland                    46
 Ireland                   38
 Chile                     26
 Denmark                   26
 Czech Republic            26
 Uruguay                   26
 Croatia                   26
 Argentina                 24
 Philippines               24
Brazil                     22
Name: country, dtype: int64

In [12]:
df['country'] = df['country'].str.lstrip()
df['country'].value_counts()

USA                     5260
Brazil                   822
Canada                   674
United Kingdom           330
Australia                320
United Arab Emirates     160
Sweden                   144
Mexico                   140
China                    122
Germany                  108
Japan                    106
Singapore                 90
Russia                    72
New Zealand               66
Netherlands               50
South Korea               48
Poland                    46
Ireland                   38
Uruguay                   26
Czech Republic            26
Chile                     26
Croatia                   26
Denmark                   26
Philippines               24
Argentina                 24
Name: country, dtype: int64

## 4. Encoding Categorical Variables

**4a. Removing `finish_details`**

In [13]:
df.dtypes[df.dtypes == 'object']

fighter           object
country           object
weight_class      object
gender            object
Stance            object
finish_details    object
dtype: object

In [14]:
df.drop(columns=['finish_details'], axis=1, inplace=True)

In [15]:
df.dtypes[df.dtypes == 'object']

fighter         object
country         object
weight_class    object
gender          object
Stance          object
dtype: object

**4b. Dummy encoding every categorical variable except `fighter`**

In [16]:
dummy_cols = [column for column in df.dtypes[df.dtypes == 'object'].index if column != 'fighter']
dummy_cols

['country', 'weight_class', 'gender', 'Stance']

In [17]:
df_dummy = pd.get_dummies(df[dummy_cols], drop_first=True)
df_dummy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8774 entries, 0 to 8773
Data columns (total 41 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   country_Australia                   8774 non-null   uint8
 1   country_Brazil                      8774 non-null   uint8
 2   country_Canada                      8774 non-null   uint8
 3   country_Chile                       8774 non-null   uint8
 4   country_China                       8774 non-null   uint8
 5   country_Croatia                     8774 non-null   uint8
 6   country_Czech Republic              8774 non-null   uint8
 7   country_Denmark                     8774 non-null   uint8
 8   country_Germany                     8774 non-null   uint8
 9   country_Ireland                     8774 non-null   uint8
 10  country_Japan                       8774 non-null   uint8
 11  country_Mexico                      8774 non-null   uint8
 12  country_Netherlands                 8774 non-null   uint8
 13  country_New Zealand                 8774 non-null   uint8
 14  country_Philippines                 8774 non-null   uint8
 15  country_Poland                      8774 non-null   uint8
 16  country_Russia                      8774 non-null   uint8
 17  country_Singapore                   8774 non-null   uint8
 18  country_South Korea                 8774 non-null   uint8
 19  country_Sweden                      8774 non-null   uint8
 20  country_USA                         8774 non-null   uint8
 21  country_United Arab Emirates        8774 non-null   uint8
 22  country_United Kingdom              8774 non-null   uint8
 23  country_Uruguay                     8774 non-null   uint8
 24  weight_class_Catch Weight           8774 non-null   uint8
 25  weight_class_Featherweight          8774 non-null   uint8
 26  weight_class_Flyweight              8774 non-null   uint8
 27  weight_class_Heavyweight            8774 non-null   uint8
 28  weight_class_Light Heavyweight      8774 non-null   uint8
 29  weight_class_Lightweight            8774 non-null   uint8
 30  weight_class_Middleweight           8774 non-null   uint8
 31  weight_class_Welterweight           8774 non-null   uint8
 32  weight_class_Women's Bantamweight   8774 non-null   uint8
 33  weight_class_Women's Featherweight  8774 non-null   uint8
 34  weight_class_Women's Flyweight      8774 non-null   uint8
 35  weight_class_Women's Strawweight    8774 non-null   uint8
 36  gender_MALE                         8774 non-null   uint8
 37  Stance_Orthodox                     8774 non-null   uint8
 38  Stance_Southpaw                     8774 non-null   uint8
 39  Stance_Switch                       8774 non-null   uint8
 40  Stance_Switch                       8774 non-null   uint8
dtypes: uint8(41)
memory usage: 419.8 KB

## 5. Scaling Numerical Variables

In [18]:
scaler_cols = [column for column in df.dtypes[((df.dtypes == 'float64') | (df.dtypes== 'int64'))].index]
scaler_cols

['odds',
 'current_lose_streak',
 'current_win_streak',
 'draw',
 'avg_SIG_STR_landed',
 'avg_SIG_STR_pct',
 'avg_SUB_ATT',
 'avg_TD_landed',
 'avg_TD_pct',
 'longest_win_streak',
 'losses',
 'total_rounds_fought',
 'total_title_bouts',
 'win_by_Decision_Majority',
 'win_by_Decision_Split',
 'win_by_Decision_Unanimous',
 'win_by_KO/TKO',
 'win_by_Submission',
 'win_by_TKO_Doctor_Stoppage',
 'wins',
 'Height_cms',
 'Reach_cms',
 'Weight_lbs',
 'age',
 'finish',
 'finish_round',
 'finish_round_time',
 'total_fight_time_secs',
 'kd_bout',
 'sig_str_landed_bout',
 'sig_str_attempted_bout',
 'sig_str_pct_bout',
 'tot_str_landed_bout',
 'tot_str_attempted_bout',
 'td_landed_bout',
 'td_attempted_bout',
 'td_pct_bout',
 'sub_attempts_bout',
 'pass_bout',
 'rev_bout',
 'win_pct',
 'adj_wins',
 'current_lose_streak_dif',
 'current_win_streak_dif',
 'longest_win_streak_dif',
 'wins_dif',
 'losses_dif',
 'total_rounds_fought_dif',
 'total_title_bouts_dif',
 'win_by_Submission_dif',
 'Height_cms_dif',
 'Reach_cms_dif',
 'age_dif',
 'avg_SIG_STR_landed_dif',
 'avg_SUB_ATT_dif',
 'avg_TD_landed_dif',
 'ko_dif',
 'adj_wins_dif']

In [19]:
df[scaler_cols].describe()

,odds,current_lose_streak,current_win_streak,draw,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_landed,avg_TD_pct,longest_win_streak,...,total_title_bouts_dif,win_by_Submission_dif,Height_cms_dif,Reach_cms_dif,age_dif,avg_SIG_STR_landed_dif,avg_SUB_ATT_dif,avg_TD_landed_dif,ko_dif,adj_wins_dif
count,8774.000000,8774.000000,8774.000000,8774.000000,7389.000000,7652.000000,7585.000000,7584.000000,7565.000000,8774.000000,...,8774.000000,8774.000000,8774.000000,8774.00000,8774.000000,6692.000000,6888.000000,6886.000000,8774.000000,8774.000000
mean,-25.310691,0.535674,0.948142,0.006610,30.037174,0.449731,0.505933,1.280899,0.316491,2.100296,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
std,277.718132,0.812976,1.501904,0.086483,19.753582,0.112750,0.644255,1.274830,0.235006,2.051145,...,1.684915,1.759636,6.433477,8.83017,5.161365,21.683464,0.854898,1.697168,2.078698,14.218828
min,-1700.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-16.000000,-13.000000,-33.020000,-187.96000,-17.000000,-128.222222,-6.000000,-11.000000,-17.000000,-112.000000
25%,-200.000000,0.000000,0.000000,0.000000,16.000000,0.390000,0.000000,0.333333,0.145000,1.000000,...,0.000000,-1.000000,-5.080000,-5.08000,-3.000000,-11.381250,-0.400000,-0.909773,-1.000000,-6.000000
50%,-110.000000,0.000000,0.000000,0.000000,28.388889,0.450000,0.333333,1.000000,0.311667,2.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,173.000000,1.000000,1.000000,0.000000,41.909091,0.510000,0.800000,1.933333,0.459167,3.000000,...,0.000000,1.000000,5.080000,5.08000,3.000000,11.381250,0.400000,0.909773,1.000000,6.000000
max,1300.000000,7.000000,16.000000,2.000000,154.000000,1.000000,7.000000,12.500000,1.000000,16.000000,...,16.000000,13.000000,33.020000,187.96000,17.000000,128.222222,6.000000,11.000000,17.000000,112.000000

In [20]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[scaler_cols])
df_scaled = pd.DataFrame(df_scaled, columns=scaler_cols)
df_scaled.describe()

,odds,current_lose_streak,current_win_streak,draw,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_landed,avg_TD_pct,longest_win_streak,...,total_title_bouts_dif,win_by_Submission_dif,Height_cms_dif,Reach_cms_dif,age_dif,avg_SIG_STR_landed_dif,avg_SUB_ATT_dif,avg_TD_landed_dif,ko_dif,adj_wins_dif
count,8.774000e+03,8.774000e+03,8.774000e+03,8.774000e+03,7.389000e+03,7.652000e+03,7.585000e+03,7.584000e+03,7.565000e+03,8.774000e+03,...,8774.000000,8774.000000,8774.000000,8774.000000,8774.000000,6692.000000,6888.000000,6886.000000,8774.000000,8774.000000
mean,1.065619e-16,-1.387108e-15,-3.947656e-16,-1.205289e-15,-4.438601e-16,2.786131e-16,1.217451e-15,-3.431971e-16,-3.993721e-16,-1.932617e-15,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
std,1.000057e+00,1.000057e+00,1.000057e+00,1.000057e+00,1.000068e+00,1.000065e+00,1.000066e+00,1.000066e+00,1.000066e+00,1.000057e+00,...,1.000057,1.000057,1.000057,1.000057,1.000057,1.000075,1.000073,1.000073,1.000057,1.000057
min,-6.030520e+00,-6.589424e-01,-6.313293e-01,-7.644029e-02,-1.520697e+00,-3.989017e+00,-7.853522e-01,-1.004827e+00,-1.346825e+00,-1.024021e+00,...,-9.496571,-7.388313,-5.132821,-21.287327,-3.293890,-5.913806,-7.018888,-6.481857,-8.178663,-7.877329
25%,-6.290524e-01,-6.589424e-01,-6.313293e-01,-7.644029e-02,-7.106622e-01,-5.297976e-01,-7.853522e-01,-7.433367e-01,-7.297783e-01,-5.364608e-01,...,0.000000,-0.568332,-0.789665,-0.575333,-0.581275,-0.524921,-0.467926,-0.536092,-0.481098,-0.422000
50%,-3.049644e-01,-6.589424e-01,-6.313293e-01,-7.644029e-02,-8.344799e-02,2.390055e-03,-2.679243e-01,-2.203567e-01,-2.052916e-02,-4.890051e-02,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.141125e-01,5.711768e-01,3.452997e-02,-7.644029e-02,6.010414e-01,5.345777e-01,4.564748e-01,5.118152e-01,6.071564e-01,4.386598e-01,...,0.000000,0.568332,0.789665,0.575333,0.581275,0.524921,0.467926,0.536092,0.481098,0.422000
max,4.772415e+00,7.951892e+00,1.002242e+01,2.305070e+01,6.275885e+00,4.880777e+00,1.008063e+01,8.801047e+00,2.908670e+00,6.776944e+00,...,9.496571,7.388313,5.132821,21.287327,3.293890,5.913806,7.018888,6.481857,8.178663,7.877329

## 6. Combine All preprocessed DataFrames

**6a. Drop original columns**

In [21]:
df.drop(columns=scaler_cols + dummy_cols, inplace=True)

In [22]:
df.columns

Index(['date', 'fighter', 'Winner', 'title_bout', 'better_rank'], dtype='object')

**6b. Concatenate preprocessed DataFrames**

In [23]:
df = pd.concat([df, df_dummy, df_scaled], axis=1)
df.columns

Index(['date', 'fighter', 'Winner', 'title_bout', 'better_rank',
       'country_Australia', 'country_Brazil', 'country_Canada',
       'country_Chile', 'country_China',
       ...
       'total_title_bouts_dif', 'win_by_Submission_dif', 'Height_cms_dif',
       'Reach_cms_dif', 'age_dif', 'avg_SIG_STR_landed_dif', 'avg_SUB_ATT_dif',
       'avg_TD_landed_dif', 'ko_dif', 'adj_wins_dif'],
      dtype='object', length=104)

**6c. Save DataFrame**

In [24]:
df.to_csv('df.csv')

## 7. Final Thoughts

Since I will have multiple dependent variables later on, I will reserve the train-test split until the Modeling section, where I can properly assess each independent variable in its own dedicated section.